### ISSUE TITLE
node server.js issue on port 80

### ISSUE THREAD

**Issue by johnfelipe** [vreelb/dewdle#4]
felipe@cloud:~/dewdle$ node server.js
	Websocket server listening on port 12180...
	events.js:182
		  throw er; // Unhandled 'error' event
		  ^

	Error: listen EACCES 0.0.0.0:80
		at Object._errnoException (util.js:1022:11)
		at _exceptionWithHostPort (util.js:1045:20)
		at Server.setupListenHandle [as _listen2] (net.js:1313:19)
		at listenInCluster (net.js:1378:12)
		at Server.listen (net.js:1478:7)
		at Function.listen (/home/felipe/dewdle/node_modules/express/lib/application.js:618:24)
		at Object.<anonymous> (/home/felipe/dewdle/server.js:15:5)
		at Module._compile (module.js:573:30)
		at Object.Module._extensions..js (module.js:584:10)
		at Module.load (module.js:507:32)

I have something in port 80, how can solve this¡?

**Comment by vreelb** [comment]
This is actually an issue I had anticipated but hadn't added the webserver option to the config yet.

Right now it should be as simple as editing line 15 of server.js, replacing '80' with whichever port you want to use. You may want to edit the next line to reflect which port that is as well, although it's just a console message.

**Comment by johnfelipe** [comment]
felipe@cloud:~/dewdle$ node server.js
	Websocket server listening on port 12180...
	events.js:182
		  throw er; // Unhandled 'error' event
		  ^

	Error: listen EACCES 0.0.0.0:81
		at Object._errnoException (util.js:1022:11)
		at _exceptionWithHostPort (util.js:1045:20)
		at Server.setupListenHandle [as _listen2] (net.js:1313:19)
		at listenInCluster (net.js:1378:12)
		at Server.listen (net.js:1478:7)
		at Function.listen (/home/felipe/dewdle/node_modules/express/lib/application.js:618:24)
		at Object.<anonymous> (/home/felipe/dewdle/server.js:15:5)
		at Module._compile (module.js:573:30)
		at Object.Module._extensions..js (module.js:584:10)
		at Module.load (module.js:507:32)

Port 81 is not working to

**Comment by vreelb** [comment]
Could you try a port that is way out of the lower range, like 8080?

**Comment by johnfelipe** [comment]
felipe@cloud:~/dewdle$ node server.js
	Websocket server listening on port 12180...
	events.js:182
		  throw er; // Unhandled 'error' event
		  ^

	Error: listen EADDRINUSE :::8080
		at Object._errnoException (util.js:1022:11)
		at _exceptionWithHostPort (util.js:1045:20)
		at Server.setupListenHandle [as _listen2] (net.js:1330:14)
		at listenInCluster (net.js:1378:12)
		at Server.listen (net.js:1478:7)
		at Function.listen (/home/felipe/dewdle/node_modules/express/lib/application.js:618:24)
		at Object.<anonymous> (/home/felipe/dewdle/server.js:15:5)
		at Module._compile (module.js:573:30)
		at Object.Module._extensions..js (module.js:584:10)
		at Module.load (module.js:507:32)

**Comment by vreelb** [comment]
So it appears that there have been a couple of issues. Most recently you're getting `EADDRINUSE` because something else is evidently using port 8080. Previously you were getting `EACCES` which means you don't have the privileges to bind to that port (usually happens in the lower port range as they are reserved for specific things).

Please try choosing a high port number that you don't have in use already.

**Comment by rubangarmon** [comment]
@johnfelipe did you resolve this issue?

**Comment by jsgcode** [comment]
@rubangarmon Hello, I had the same problem. I just solved it by setting port in 7777. I'm using gcloud. Apparently ports 80, 8080 and 3080 were busy or something.

**Comment by jsgcode** [comment]
@johnfelipe Hello, I had the same problem. I just solved it by configuring the port in 7777.
I'm using gcloud.
Apparently ports 80, 8080 and 3080 were busy or something like that.

**Comment by vreelb** [comment]
Closing this as it has been multiple years without comment and was a configuration issue.
